Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using Mission9Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission9Project.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository repo { get; set; }
        private Basket basket { get; set; }

        public PurchaseController (IPurchaseRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            // conditional statements to check cart status
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Your cart is empty.");
            }
            
            if (ModelState.IsValid)
            {
                purchase.Lines = basket.Items.ToArray();
                repo.SavePurchase(purchase);
                basket.ClearBasket();

                return RedirectToPage("/Confirmation");
            }
            else
            {
                return View();
            }
        }
    }
}

Pages/Confirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Mission9Project.Pages
{
    public class ConfirmationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shop.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mission9Project.Infrastructure;
using Mission9Project.Models;

namespace Mission9Project.Pages
{
    public class ShopModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }

        public ShopModel (IBookstoreRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        public Basket basket { get; set; }

        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookid, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == bookid).Book);

            return RedirectToPage(new { ReturnUrl = returnUrl});
        }
    }
}

Pages/Confirmation.cshtml
@page
@model Mission9Project.Pages.ConfirmationModel
@{
}

<div class="text-center">
    <h2> Your purchase is completed!</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

Pages/Shop.cshtml
@page
@model Mission9Project.Pages.ShopModel
@{
}

<h2>Shopping Cart</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    
    <tbody>
        @foreach(var i in Model.basket.Items)
         {
            <tr style="background-color: #E6F1F6">
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>$@i.Book.Price</td>
                <td>@((i.Quantity * i.Book.Price).ToString("c"))</td>

                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@i.Book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
         }

    </tbody>

    <tfood>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfood>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Purchase">Checkout</a>
</div>

Pages/_ShopLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        Bookstore
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>